//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using INFINITE.CORE.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Data.Base;

namespace INFINITE.CORE.Core.Response
{
    public partial class RoleResponse: BaseStringEntity, IMapResponse<RoleResponse, INFINITE.CORE.Data.Model.Role>
    {
		public bool Active{ get; set; }
		public string Name{ get; set; }

        public void Mapping(IMappingExpression<INFINITE.CORE.Data.Model.Role, RoleResponse> map)
        {
            //use this for mapping
            //map.ForMember(d => d.object, opt => opt.MapFrom(s => s.EF_COLUMN));

        }
    }
}

