//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using INFINITE.CORE.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Data.Base;

namespace INFINITE.CORE.Core.Response
{
    public partial class EmailTemplateResponse: BaseGuidEntity, IMapResponse<EmailTemplateResponse, INFINITE.CORE.Data.Model.EmailTemplate>
    {
		public string DisplayName{ get; set; }
		public string MailContent{ get; set; }
		public string MailFrom{ get; set; }
		public string Module{ get; set; }
		public string Subject{ get; set; }


        public void Mapping(IMappingExpression<INFINITE.CORE.Data.Model.EmailTemplate, EmailTemplateResponse> map)
        {
            //use this for mapping
            //map.ForMember(d => d.object, opt => opt.MapFrom(s => s.EF_COLUMN));

        }
    }
}

