//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace INFINITE.CORE.Core.Request
{
    public partial class EmailTemplateRequest
    {
		[Required]
		public string DisplayName{ get; set; }
		[Required]
		public string MailContent{ get; set; }
		[Required]
		public string MailFrom{ get; set; }
		[Required]
		public string Module{ get; set; }
		[Required]
		public string Subject{ get; set; }

    }
}

