//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using INFINITE.CORE.Data;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Response;

namespace INFINITE.CORE.Core.EmailTemplate.Query
{

    public class GetEmailTemplateByIdRequest : IRequest<ObjectResponse<EmailTemplateResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetEmailTemplateByIdHandler : IRequestHandler<GetEmailTemplateByIdRequest, ObjectResponse<EmailTemplateResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetEmailTemplateByIdHandler(
            ILogger<GetEmailTemplateByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<EmailTemplateResponse>> Handle(GetEmailTemplateByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<EmailTemplateResponse> result = new ObjectResponse<EmailTemplateResponse>();
            try
            {
                var item = await _context.Entity<INFINITE.CORE.Data.Model.EmailTemplate>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<EmailTemplateResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id INFINITE.CORE.Data.Model.EmailTemplate {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail EmailTemplate", request.Id);
                result.Error("Failed Get Detail EmailTemplate", ex.Message);
            }
            return result;
        }
    }
}

