//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using INFINITE.CORE.Data;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Response;

namespace INFINITE.CORE.Core.Config.Query
{

    public class GetConfigByIdRequest : IRequest<ObjectResponse<ConfigResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetConfigByIdHandler : IRequestHandler<GetConfigByIdRequest, ObjectResponse<ConfigResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetConfigByIdHandler(
            ILogger<GetConfigByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<ConfigResponse>> Handle(GetConfigByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<ConfigResponse> result = new ObjectResponse<ConfigResponse>();
            try
            {
                var item = await _context.Entity<INFINITE.CORE.Data.Model.Config>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<ConfigResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id INFINITE.CORE.Data.Model.Config {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Config", request.Id);
                result.Error("Failed Get Detail Config", ex.Message);
            }
            return result;
        }
    }
}

