//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using INFINITE.CORE.Data;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Response;
using DocumentFormat.OpenXml.Spreadsheet;

namespace INFINITE.CORE.Core.User.Query
{

    public class GetUserByIdRequest : IRequest<ObjectResponse<UserDetailResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetUserByIdHandler : IRequestHandler<GetUserByIdRequest, ObjectResponse<UserDetailResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetUserByIdHandler(
            ILogger<GetUserByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<UserDetailResponse>> Handle(GetUserByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<UserDetailResponse> result = new ObjectResponse<UserDetailResponse>();
            try
            {
                var item = await _context.Entity<INFINITE.CORE.Data.Model.User>().Where(d => d.Id == request.Id)
                    .Include(d=>d.UserRole).ThenInclude(d=>d.IdRoleNavigation).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<UserDetailResponse>(item);
                    result.Data.Roles = item.UserRole.Select(d => new ReferensiStringObject()
                    {
                        Id = d.IdRole,
                        Nama = d.IdRoleNavigation.Name
                    }).ToList();
                    result.OK();
                }
                else
                    result.NotFound($"Id User {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail User", request.Id);
                result.Error("Failed Get Detail User", ex.Message);
            }
            return result;
        }
    }
}

