//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace INFINITE.CORE.Core.Request
{
    public partial class UserRoleRequest
    {
		[Required]
		public string IdRole{ get; set; }
		[Required]
		public Guid IdUser{ get; set; }

    }
}

