//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using INFINITE.CORE.Data;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Helper;
using INFINITE.CORE.Core.Request;
using Microsoft.EntityFrameworkCore;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Data.Provider;

namespace INFINITE.CORE.Core.Role.Command
{

    #region Request
    public class AddRoleMapping: Profile
    {
        public AddRoleMapping()
        {
            CreateMap<AddRoleRequest, RoleRequest>().ReverseMap();
        }
    }
    public class AddRoleRequest :RoleRequest, IMapRequest<INFINITE.CORE.Data.Model.Role, AddRoleRequest>,IRequest<StatusResponse>
    {
        [Required]
        public string Inputer { get; set; }
        public void Mapping(IMappingExpression<AddRoleRequest, INFINITE.CORE.Data.Model.Role> map)
        {
            //use this for mapping
            //map.ForMember(d => d.EF_COLUMN, opt => opt.MapFrom(s => s.Object));
        }
    }
    #endregion

    internal class AddRoleHandler : IRequestHandler<AddRoleRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public AddRoleHandler(
            ILogger<AddRoleHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<StatusResponse> Handle(AddRoleRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                if (request.Permissions != null && request.Permissions.Count > 0)
                {
                    request.Permissions = request.Permissions.GroupBy(x => x).Select(x => x.Key).ToList();
                    var checkPermissions = request.Permissions.Any(x => !Permissions.List().Any(z => z == x));
                    if (checkPermissions)
                    {
                        result.BadRequest("Permissions doesn't exists.");
                        return result;
                    }
                };

                var data = _mapper.Map<INFINITE.CORE.Data.Model.Role>(request);
                data.CreateBy = request.Inputer;
                data.CreateDate = DateTime.Now;
                data.RolePermissions = request.Permissions.Select(x => new RolePermissions
                {
                    CreateBy = request.Inputer,
                    CreateDate = DateTime.Now,
                    IdRole = data.Id,
                    Permission = x
                }).ToList();
                var add = await _context.AddSave(data);
                if (add.Success)
                    result.OK();
                else
                    result.BadRequest(add.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Add Role", request);
                result.Error("Failed Add Role", ex.Message);
            }
            return result;
        }
    }
}

