//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using INFINITE.CORE.Data;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Helper;
using INFINITE.CORE.Core.Request;
using INFINITE.CORE.Data.Provider;
using INFINITE.CORE.Data.Model;

namespace INFINITE.CORE.Core.Role.Command
{

    #region Request
    public class EditRoleMapping: Profile
    {
        public EditRoleMapping()
        {
            CreateMap<EditRoleRequest, RoleRequest>().ReverseMap();
        }
    }
    public class EditRoleRequest :RoleRequest, IMapRequest<INFINITE.CORE.Data.Model.Role, EditRoleRequest>,IRequest<StatusResponse>
    {
        [Required]
        public string Inputer { get; set; }
        public void Mapping(IMappingExpression<EditRoleRequest, INFINITE.CORE.Data.Model.Role> map)
        {
            //use this for mapping
            //map.ForMember(d => d.EF_COLUMN, opt => opt.MapFrom(s => s.Object));
        }
    }
    #endregion

    internal class EditRoleHandler : IRequestHandler<EditRoleRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public EditRoleHandler(
            ILogger<EditRoleHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<StatusResponse> Handle(EditRoleRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                if (request.Permissions != null && request.Permissions.Count > 0)
                {
                    request.Permissions = request.Permissions.GroupBy(x => x).Select(x => x.Key).ToList();
                    var checkPermissions = request.Permissions.Any(x => !Permissions.List().Any(z => z == x));
                    if (checkPermissions)
                    {
                        result.BadRequest("Permissions doesn't exists.");
                        return result;
                    }
                };

                var existingItems = await _context.Entity<INFINITE.CORE.Data.Model.Role>().Where(d => d.Id == request.Id).Include(x => x.RolePermissions).FirstOrDefaultAsync();
                if (existingItems != null)
                {
                    var item = _mapper.Map(request, existingItems);
                    item.UpdateBy = request.Inputer;
                    item.UpdateDate = DateTime.Now;

                    existingItems.RolePermissions.Clear();
                    foreach (var permission in request.Permissions)
                    {
                        existingItems.RolePermissions.Add(new RolePermissions
                        {
                            CreateBy = request.Inputer,
                            CreateDate = DateTime.Now,
                            IdRole = existingItems.Id,
                            Permission = permission
                        });
                    }

                    var update = await _context.UpdateSave(item);
                    if (update.Success)
                        result.OK();
                    else
                        result.BadRequest(update.Message);

                    return result;
                }
                else
                    result.NotFound($"Id Role {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Edit Role", request);
                result.Error("Failed Edit Role", ex.Message);
            }
            return result;
        }
    }
}

