//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using INFINITE.CORE.Data;
using INFINITE.CORE.Data.Model;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Response;
using INFINITE.CORE.Core.Helper;

namespace INFINITE.CORE.Core.Repository.Query
{
    public class GetRepositoryListRequest : ListRequest,IListRequest<GetRepositoryListRequest>,IRequest<ListResponse<RepositoryResponse>>
    {
    }
    internal class GetRepositoryListHandler : IRequestHandler<GetRepositoryListRequest, ListResponse<RepositoryResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetRepositoryListHandler(
            ILogger<GetRepositoryListHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }

        public async Task<ListResponse<RepositoryResponse>> Handle(GetRepositoryListRequest request, CancellationToken cancellationToken)
        {
            ListResponse<RepositoryResponse> result = new ListResponse<RepositoryResponse>();
            try
            {
				var query = _context.Entity<INFINITE.CORE.Data.Model.Repository>().AsQueryable();

				#region Filter
				Expression<Func<INFINITE.CORE.Data.Model.Repository, object>> column_sort = null;
				List<Expression<Func<INFINITE.CORE.Data.Model.Repository, bool>>> where = new List<Expression<Func<INFINITE.CORE.Data.Model.Repository, bool>>>();
				if (request.Filter != null && request.Filter.Count > 0)
				{
					foreach (var f in request.Filter)
					{
						var obj = ListExpression(f.Search, f.Field, true);
						if (obj.where != null)
							where.Add(obj.where);
					}
				}
				if (where != null && where.Count() > 0)
				{
					foreach (var w in where)
					{
						query = query.Where(w);
					}
				}
				if (request.Sort != null)
                {
					column_sort = ListExpression(request.Sort.Field, request.Sort.Field, false).order!;
					if(column_sort != null)
						query = request.Sort.Type == SortTypeEnum.ASC ? query.OrderBy(column_sort) : query.OrderByDescending(column_sort);
					else
						query = query.OrderBy(d=>d.Id);
				}
				#endregion

				var query_count = query;
				if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
					query = query.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value);
				var data_list = await query.ToListAsync();

				result.List = _mapper.Map<List<RepositoryResponse>>(data_list);
				result.Filtered = data_list.Count();
				result.Count = await query_count.CountAsync();
				result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List Repository", request);
                result.Error("Failed Get List Repository", ex.Message);
            }
            return result;
        }

        #region List Utility
		private (Expression<Func<INFINITE.CORE.Data.Model.Repository, bool>> where, Expression<Func<INFINITE.CORE.Data.Model.Repository, object>> order) ListExpression(string search, string field, bool is_where)
		{
			Expression<Func<INFINITE.CORE.Data.Model.Repository, object>> result_order = null;
			Expression<Func<INFINITE.CORE.Data.Model.Repository, bool>> result_where = null;
            if (!string.IsNullOrWhiteSpace(search) && !string.IsNullOrWhiteSpace(field))
            {
                field = field.Trim().ToLower();
                search = search.Trim().ToLower();
                switch (field)
                {
					case "id" : 
						if(is_where){
							if (Guid.TryParse(search, out var _Id))
								result_where = (d=>d.Id == _Id);
                            else
                                result_where = (d => d.Id == Guid.Empty);
                        }
						else
							result_order = (d => d.Id);
					break;
					case "code" : 
						if(is_where){
							result_where = (d=>d.Code.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Code);
					break;
					case "createby" : 
						if(is_where){
							result_where = (d=>d.CreateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.CreateBy);
					break;
					case "createdate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _CreateDate))
								result_where = (d=>d.CreateDate == _CreateDate);
						}
						else
							result_order = (d => d.CreateDate);
					break;
					case "description" : 
						if(is_where){
							result_where = (d=>d.Description.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Description);
					break;
					case "extension" : 
						if(is_where){
							result_where = (d=>d.Extension.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Extension);
					break;
					case "filename" : 
						if(is_where){
							result_where = (d=>d.FileName.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.FileName);
					break;
					case "ispublic" : 
						if(is_where){
							if (bool.TryParse(search, out var _IsPublic))
								result_where = (d=>d.IsPublic == _IsPublic);
						}
						else
							result_order = (d => d.IsPublic);
					break;
					case "mimetype" : 
						if(is_where){
							result_where = (d=>d.MimeType.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.MimeType);
					break;
					case "modul" : 
						if(is_where){
							result_where = (d=>d.Modul.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Modul);
					break;

                }
            }
            return (result_where, result_order);
        }
        #endregion
    }
}

