//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using INFINITE.CORE.Data.Base.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using INFINITE.CORE.Data;
using INFINITE.CORE.Shared.Attributes;
using INFINITE.CORE.Core.Helper;
using Microsoft.Extensions.Options;

namespace INFINITE.CORE.Core.Repository.Command
{

    #region Request
    public class DeleteRepositoryRequest : IRequest<StatusResponse>
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        public string Inputer { get; set; }
    }
    #endregion

    internal class DeleteRepositoryHandler : IRequestHandler<DeleteRepositoryRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly ApplicationConfig _config;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public DeleteRepositoryHandler(
            ILogger<DeleteRepositoryHandler> logger,
            IOptions<ApplicationConfig> options,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _config = options.Value;
            _mediator = mediator;
            _context = context;
        }
        public async Task<StatusResponse> Handle(DeleteRepositoryRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var item = await _context.Entity<Data.Model.Repository>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                var path = Path.Combine(_config.MediaPath, request.Id.ToString());
                if (item != null)
                {
                    var delete = await _context.DeleteSave(item);
                    if (delete.Success)
                    {
                        if (File.Exists(path))
                           File.Delete(path);
                        result.OK();
                    }
                    else
                        result.BadRequest(delete.Message);

                    return result;
                }
                else
                    result.NotFound($"Id Media {request.Id} Tidak Ditemukan");

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Delete Repository", request.Id);
                result.Error("Failed Delete Repository", ex.Message);
            }
            return result;
        }
    }
}

